### ISSUE TITLE
A couple of errors with the Spanish (esES) client

### ISSUE THREAD

**Issue by woopydalan** [elysium-project/server#1932]
Hello,

As it turns out, Blizzard needed to make a special patch 1.12.2 for the spanish client. I was wondering if there was any way this could be sorted out in a patch.
 ```
World of Warcraft Client Patch 1.12.2 (http://wowwiki.wikia.com/wiki/Patch_1.12.2)

Bugs

    Fixed an issue where players were unable to resurrect at a Spirit Healer. (Spanish Only)
    Fixed several issues with in-game slash commands. (Spanish Only)
```
With Regards to the slash command issue, what happens is you can't use the english slash commands. For example, I can't type /w, I must use /susurrar to whisper, same goes for all the other commands that I have found.

With regards to the spirit healer, the problem is when you try to resurrect at the spirit healer with the spanish client, you get this error:

[2017/08/04 22:47:06-262]: FrameXML\StaticPopup.lua:1140: bad argument #3 to `format' (number expected, got no value)
<in C code>: in function `format'
FrameXML\StaticPopup.lua:1140: in function `OnAccept'
FrameXML\StaticPopup.lua:1855: in function `StaticPopup_OnClick'
<string>:"StaticPopup1Button1:OnClick":2: in main chunk

  ---

**Comment by ifyousayso** [comment]
Interesting.. and if you make a copy of the game and patch it to 1.12.2, the server won't let you play?

**Comment by EinBaum** [comment]
I heard that it's definitely possible to play on Elysium with client patch 1.12.2

**Comment by woopydalan** [comment]
The problem is that no one knows where to find patch 1.12.2 in spanish, its been lost in the sands of time

**Comment by thepparker** [comment]
Not related to server development. Post on the forums for support, best of luck finding the Spanish client patch.

**Comment by woopydalan** [comment]
There's no way this can be fixed server side? People have been looking for months for the patch and can't find it

**Comment by thepparker** [comment]
We don't have control over client chat commands or the client's LUA

**Comment by ifyousayso** [comment]
The slash command is easy to fix and I can send you a modified LUA function with some number (say 0) for your client to process, but what it does with that value, if anything, can lead to any results.

I'll look for the official patch and update this message if I find anything.

**Comment by woopydalan** [comment]
@ifyousayso

Thanks a lot, I'm not a programmer but if it's easy enough I should be able to fix. Is it possible to make it so both English and Spanish commands work? 

As far as the spirit resurrect is concerned, I'm not sure where to begin on that one

**Comment by ifyousayso** [comment]
Okay, so as far as I can tell, everything core-related is in wow.exe, which happens to be language-neutral. That means that if you just copy wow.exe, version 1.12.1(.5875) from another language version and replace yours (make a backup of yours), the Spirit Healer issue should be fixed. I have checked my StaticPopup.lua:1140 and it has only 2 arguments, making me think that it's not the lua but the core that's messed up.
At http://elysium.foshin.com/wowexe1121.zip you can find the file I am using (enGB) but if you don't trust me, DO NOT download or run.

For the slash command issue, GlobalStrings.lua contains something similar to this:
SLASH_WHISPER8 = "/t"; -- Whisper
SLASH_WHISPER9 = "/tell"; -- Whisper
SLASH_WHISPER3 = "/t"; -- Whisper
SLASH_WHISPER6 = "/w"; -- Whisper
SLASH_WHISPER5 = "/send"; -- Whisper
SLASH_WHISPER4 = "/tell"; -- Whisper
SLASH_WHISPER1 = "/w"; -- Whisper
SLASH_WHISPER2 = "/whisper"; -- Whisper
SLASH_WHISPER7 = "/whisper"; -- Whisper
SLASH_WHISPER10 = "/send"; -- Whisper

Now, either I install the esES version just to extract that file, or you send me your (wow/data/)patch-2.mpq to woopydalan@foshin.com . I can then extract the file, select some SLASH_WHISPERx that's a duplicate and overwrite it with "/w" in a tiny addon.

**Comment by ifyousayso** [comment]
Addon: http://elysium.foshin.com/englishcommands.zip

It overwrites some duplicate slash commands and is mainly for the 1.12.1 Spanish to English version. Password for the file above is 1121.. sorry 'bout that.

I haven't tested any of it.. let me know if something doesn't work.

**Comment by woopydalan** [comment]
@ifyousayso the addon works great, thanks a lot

As far as the ressurect goes, it seems that even though I am using your wow.exe, I still get the error

[2017/08/09 05:50:37-421]: FrameXML\StaticPopup.lua:1140: bad argument #3 to `format' (number expected, got no value)
<in C code>: in function `format'
FrameXML\StaticPopup.lua:1140: in function `OnAccept'
FrameXML\StaticPopup.lua:1855: in function `StaticPopup_OnClick'
<string>:"StaticPopup1Button1:OnClick":2: in main chunk

  ---

**Comment by ifyousayso** [comment]
HA! Stupid me.. found and fixed the resurrection issue as well. Get it at:
http://elysium.foshin.com/spanishfix.zip
This addon takes care of the slash commands too so you can delete the other one.

**Comment by woopydalan** [comment]
@ifyousayso I want to thank you on behalf of the spanish WoW community!!
